import type { LearningLanguageId } from '../learningTracks'

/** Shared across tracks — extend per-language below. */
export const BASE_KEYWORDS: readonly string[] = [
  'if',
  'else',
  'elif',
  'for',
  'while',
  'do',
  'switch',
  'case',
  'break',
  'continue',
  'return',
  'try',
  'catch',
  'finally',
  'throw',
  'new',
  'this',
  'super',
  'class',
  'extends',
  'implements',
  'import',
  'export',
  'from',
  'default',
  'package',
  'public',
  'private',
  'protected',
  'static',
  'void',
  'int',
  'long',
  'short',
  'byte',
  'float',
  'double',
  'char',
  'boolean',
  'true',
  'false',
  'null',
  'var',
  'let',
  'const',
  'function',
  'async',
  'await',
  'typeof',
  'instanceof',
  'def',
  'fn',
  'fun',
  'func',
  'mut',
  'val',
  'type',
  'interface',
  'enum',
  'struct',
  'union',
  'namespace',
  'using',
  'template',
  'typename',
  'virtual',
  'override',
  'constexpr',
  'decltype',
  'auto',
  'volatile',
  'goto',
  'sizeof',
  'typedef',
  'extern',
  'register',
  'inline',
  'restrict',
  'SELECT',
  'FROM',
  'WHERE',
  'INSERT',
  'UPDATE',
  'DELETE',
  'VALUES',
  'ORDER',
  'BY',
  'GROUP',
  'HAVING',
  'JOIN',
  'INNER',
  'LEFT',
  'RIGHT',
  'OUTER',
  'ON',
  'AS',
  'AND',
  'OR',
  'NOT',
  'LIMIT',
  'OFFSET',
  'WITH',
  'RECURSIVE',
  'CASE',
  'WHEN',
  'THEN',
  'END',
  'BEGIN',
  'COMMIT',
  'ROLLBACK',
  'TRANSACTION',
]

const EXTRA: Partial<Record<LearningLanguageId, readonly string[]>> = {
  javascript: ['undefined', 'yield', 'of', 'in', 'delete', 'void', 'debugger', 'with'],
  typescript: ['undefined', 'never', 'unknown', 'keyof', 'readonly', 'infer', 'is', 'asserts', 'satisfies'],
  python: [
    'and',
    'or',
    'not',
    'in',
    'is',
    'lambda',
    'pass',
    'global',
    'nonlocal',
    'True',
    'False',
    'None',
    'self',
    'yield',
    'with',
    'as',
    'assert',
    'del',
    'except',
    'raise',
    'from',
    'import',
    'match',
    'case',
  ],
  java: ['String', 'Integer', 'Boolean', 'Object', 'var', 'record', 'sealed', 'permits', 'yield', 'when'],
  csharp: [
    'var',
    'string',
    'bool',
    'object',
    'dynamic',
    'checked',
    'unchecked',
    'stackalloc',
    'nameof',
    'params',
    'ref',
    'out',
    'in',
    'is',
    'as',
    'base',
    'operator',
    'implicit',
    'explicit',
    'event',
    'delegate',
    'where',
    'select',
    'from',
    'into',
    'orderby',
    'ascending',
    'descending',
    'group',
    'by',
    'join',
    'on',
    'equals',
    'let',
    'get',
    'set',
    'init',
    'required',
    'file',
    'scoped',
    'partial',
    'record',
    'with',
    'add',
    'remove',
  ],
  cpp: [
    'std',
    'cout',
    'cin',
    'endl',
    'namespace',
    'using',
    'public',
    'private',
    'protected',
    'template',
    'typename',
    'friend',
    'explicit',
    'virtual',
    'override',
    'final',
    'noexcept',
    'constexpr',
    'decltype',
    'concept',
    'requires',
    'co_await',
    'co_return',
    'co_yield',
  ],
  c_lang: ['size_t', 'NULL', 'struct', 'union', 'enum', 'typedef', 'sizeof', 'restrict', 'inline', 'extern'],
  go: [
    'package',
    'func',
    'map',
    'chan',
    'range',
    'select',
    'defer',
    'go',
    'fallthrough',
    'iota',
    'nil',
    'make',
    'len',
    'cap',
    'append',
    'copy',
    'delete',
    'panic',
    'recover',
    'interface',
    'struct',
    'type',
    'const',
    'var',
  ],
  rust: [
    'crate',
    'super',
    'self',
    'Self',
    'where',
    'trait',
    'impl',
    'pub',
    'mod',
    'use',
    'move',
    'ref',
    'mut',
    'dyn',
    'match',
    'if',
    'else',
    'loop',
    'while',
    'for',
    'in',
    'break',
    'continue',
    'return',
    'async',
    'await',
    'unsafe',
    'extern',
    'type',
    'struct',
    'enum',
    'union',
    'let',
    'static',
    'const',
    'fn',
    'impl',
    'trait',
    'true',
    'false',
    'Some',
    'None',
    'Ok',
    'Err',
  ],
  swift: [
    'internal',
    'fileprivate',
    'open',
    'public',
    'private',
    'protocol',
    'extension',
    'associatedtype',
    'subscript',
    'indirect',
    'optional',
    'mutating',
    'nonmutating',
    'lazy',
    'weak',
    'unowned',
    'defer',
    'guard',
    'fallthrough',
    'where',
    'is',
    'as',
    'try',
    'throws',
    'rethrows',
    'inout',
    'some',
    'Self',
    'self',
    'init',
    'deinit',
    'willSet',
    'didSet',
    'get',
    'set',
    'in',
    'repeat',
    'import',
    'typealias',
    'print',
    'associatedtype',
    'indirect',
    'case',
    'default',
    'fallthrough',
    'switch',
    'break',
    'continue',
    'return',
    'for',
    'while',
    'repeat',
    'if',
    'else',
    'guard',
    'defer',
    'func',
    'let',
    'var',
    'enum',
    'struct',
    'class',
    'actor',
    'extension',
    'protocol',
    'import',
    'nil',
    'true',
    'false',
  ],
  kotlin: [
    'fun',
    'val',
    'var',
    'when',
    'object',
    'open',
    'abstract',
    'sealed',
    'data',
    'inline',
    'infix',
    'lateinit',
    'companion',
    'init',
    'by',
    'get',
    'set',
    'field',
    'typeof',
    'is',
    'as',
    'in',
    'out',
    'reified',
    'suspend',
    'crossinline',
    'noinline',
    'tailrec',
    'operator',
    'infix',
    'external',
    'annotation',
    'constructor',
    'typeof',
    'throw',
    'try',
    'catch',
    'finally',
    'package',
    'import',
    'null',
    'true',
    'false',
  ],
  ruby: [
    'module',
    'class',
    'def',
    'end',
    'if',
    'unless',
    'elsif',
    'else',
    'while',
    'until',
    'for',
    'in',
    'do',
    'begin',
    'rescue',
    'ensure',
    'retry',
    'redo',
    'next',
    'break',
    'return',
    'yield',
    'super',
    'self',
    'nil',
    'true',
    'false',
    'and',
    'or',
    'not',
    'alias',
    'undef',
    'defined',
    'then',
    'case',
    'when',
    'BEGIN',
    'END',
  ],
  php: [
    'echo',
    'print',
    'isset',
    'empty',
    'array',
    'callable',
    'iterable',
    'insteadof',
    'trait',
    'namespace',
    'use',
    'const',
    'parent',
    'self',
    'static',
    'abstract',
    'final',
    'readonly',
    'match',
    'fn',
    'list',
    'global',
    'var',
    'endif',
    'endwhile',
    'endfor',
    'endforeach',
    'endswitch',
    'declare',
    'ticks',
    'strict_types',
  ],
  sql: ['DISTINCT', 'ALL', 'UNION', 'INTERSECT', 'EXCEPT', 'CAST', 'COALESCE', 'NULLIF', 'EXISTS', 'BETWEEN', 'LIKE', 'ILIKE', 'IS', 'TRUE', 'FALSE', 'NULL'],
  html_css: ['style', 'script', 'div', 'span', 'class', 'id', 'href', 'src', 'rel', 'type', 'media', 'import', 'keyframes', 'from', 'to', 'important'],
  dart: [
    'void',
    'dynamic',
    'late',
    'required',
    'covariant',
    'factory',
    'mixin',
    'extension',
    'on',
    'operator',
    'typedef',
    'external',
    'library',
    'part',
    'export',
    'show',
    'hide',
    'with',
    'assert',
    'async',
    'await',
    'yield',
    'sync',
    'get',
    'set',
    'super',
    'this',
    'new',
    'is',
    'as',
    'in',
    'assert',
  ],
  lua: [
    'and',
    'or',
    'not',
    'then',
    'elseif',
    'end',
    'function',
    'local',
    'repeat',
    'until',
    'break',
    'return',
    'goto',
    'in',
    'nil',
    'true',
    'false',
  ],
  shell_bash: [
    'if',
    'then',
    'else',
    'elif',
    'fi',
    'for',
    'while',
    'until',
    'do',
    'done',
    'case',
    'esac',
    'select',
    'function',
    'time',
    'coproc',
    'in',
  ],
  r_lang: [
    'if',
    'else',
    'repeat',
    'while',
    'function',
    'for',
    'in',
    'next',
    'break',
    'TRUE',
    'FALSE',
    'NULL',
    'NA',
    'Inf',
    'NaN',
  ],
  scala: [
    'def',
    'val',
    'var',
    'lazy',
    'implicit',
    'object',
    'trait',
    'extends',
    'with',
    'case',
    'match',
    'if',
    'else',
    'for',
    'yield',
    'while',
    'do',
    'return',
    'throw',
    'try',
    'catch',
    'finally',
    'package',
    'import',
    'new',
    'super',
    'this',
    'true',
    'false',
    'null',
    'type',
    'class',
    'abstract',
    'final',
    'sealed',
    'private',
    'protected',
    'override',
  ],
  elixir: [
    'def',
    'defp',
    'defmodule',
    'defmacro',
    'defprotocol',
    'defimpl',
    'import',
    'alias',
    'require',
    'use',
    'if',
    'unless',
    'cond',
    'case',
    'fn',
    'do',
    'end',
    'try',
    'rescue',
    'after',
    'else',
    'catch',
    'receive',
    'send',
    'raise',
    'throw',
    'nil',
    'true',
    'false',
    'when',
    'and',
    'or',
    'not',
    'in',
  ],
  haskell: [
    'case',
    'of',
    'if',
    'then',
    'else',
    'let',
    'in',
    'where',
    'data',
    'newtype',
    'type',
    'class',
    'instance',
    'deriving',
    'module',
    'import',
    'qualified',
    'hiding',
    'as',
    'default',
    'do',
    'mdo',
    'rec',
    'proc',
    'infix',
    'infixl',
    'infixr',
    'forall',
    'foreign',
    'ccall',
    'safe',
    'unsafe',
    'True',
    'False',
    'Nothing',
    'Just',
  ],
}

export function buildKeywordSet(lang: LearningLanguageId): Set<string> {
  const s = new Set<string>(BASE_KEYWORDS)
  const ex = EXTRA[lang]
  if (ex) for (const w of ex) s.add(w)
  return s
}

/** Calls / output builtins to tint emerald (like `console.log` in the reference). */
export function emeraldCallRegexes(lang: LearningLanguageId): readonly RegExp[] {
  const jsFamily: RegExp[] = [/console\.(log|error|warn|info|debug)\b/g]
  const sysOut = [/System\.out\.println\b/g, /System\.out\.print\b/g]
  const fmt = [/fmt\.Print(ln|f)?\b/g]
  const rustPrint = [/println!\s*\(/g, /print!\s*\(/g, /eprintln!\s*\(/g]
  const cppOut = [/\bstd::cout\b/g, /\bstd::cerr\b/g]
  const phpEcho = [/\becho\b/g, /\bprint\s*\(/g]
  const rb = [/\bputs\b/g, /\bp\s*\(/g]
  const dartPrint = [/\bdebugPrint\s*\(/g, /\bprint\s*\(/g]
  const luaPrint = [/\bprint\s*\(/g]
  const bashEcho = [/\becho\b/g, /\bprintf\b/g]
  const rPrint = [/\bprint\s*\(/g, /\bcat\s*\(/g]
  const scalaPredef = [/\bprintln\s*\(/g, /\bprint\s*\(/g]
  const elixirIO = [/\bIO\.(puts|inspect|write)\b/g]
  const hsPut = [/\bputStrLn\b/g]
  const kotlinPrint = [/\bprintln\s*\(/g, /\bprint\s*\(/g]

  switch (lang) {
    case 'javascript':
    case 'typescript':
      return jsFamily
    case 'python':
      return [/\bprint\s*\(/g, ...jsFamily]
    case 'java':
      return [...sysOut]
    case 'kotlin':
      return [...sysOut, ...kotlinPrint]
    case 'csharp':
      return [/\bConsole\.Write(Line)?\b/g]
    case 'cpp':
    case 'c_lang':
      return cppOut
    case 'go':
      return fmt
    case 'rust':
      return rustPrint
    case 'swift':
      return []
    case 'ruby':
      return rb
    case 'php':
      return phpEcho
    case 'sql':
      return []
    case 'html_css':
      return []
    case 'dart':
      return dartPrint
    case 'lua':
      return luaPrint
    case 'shell_bash':
      return bashEcho
    case 'r_lang':
      return rPrint
    case 'scala':
      return scalaPredef
    case 'elixir':
      return elixirIO
    case 'haskell':
      return hsPut
    case 'blocks':
      return []
    default:
      return jsFamily
  }
}
